Fix missing namespace in identityref field
When we generate python code from Yang module, the restriction_arg for
the field doesn't include module name as the prefix. This is a problem
in ietf-routing model as augmented by ietf-ipv4-unicast-routing, where
the model looks like:

  module: ietf-routing
    +--rw routing
    |  +--rw router-id?                 yang:dotted-quad {router-id}?
    |  +--ro interfaces
    |  |  +--ro interface*   if:interface-ref
    |  +--rw control-plane-protocols
    |  |  +--rw control-plane-protocol* [type name]
    |  |     +--rw type             identityref
    |  |     +--rw name             string

And the example operational state from the RFC contains:

  {
    "ietf-routing:routing": {
      "router-id": "192.0.2.1",
      "control-plane-protocols": {
        "control-plane-protocol": [
          {
          "type": "ietf-routing:static",
          "name": "st0",
	  ...

Which fails to load with:

    ValueError: ietf-routing:static does not match a restricted type

    During handling of the above exception, another exception occurred:
    ...
    ValueError: {'error-string': 'type must be of a type compatible with identityref', 'defined-type': 'ietf-routing:identityref', 'generated-type': 'YANGDynClass(base=RestrictedClassType(base_type=six.text_type, restriction_type="dict_key", restriction_arg={\'routing-protocol\': {\'@module\': \'ietf-routing\', \'@namespace\': \'urn:ietf:params:xml:ns:yang:ietf-routing\'}, \'rt:routing-protocol\': {\'@module\': \'ietf-routing\', \'@namespace\': \'urn:ietf:params:xml:ns:yang:ietf-routing\'}, \'direct\': {\'@module\': \'ietf-routing\', \'@namespace\': \'urn:ietf:params:xml:ns:yang:ietf-routing\'}, \'rt:direct\': {\'@module\': \'ietf-routing\', \'@namespace\': \'urn:ietf:params:xml:ns:yang:ietf-routing\'}, \'static\': {\'@module\': \'ietf-routing\', \'@namespace\': \'urn:ietf:params:xml:ns:yang:ietf-routing\'}, \'rt:static\': {\'@module\': \'ietf-routing\', \'@namespace\': \'urn:ietf:params:xml:ns:yang:ietf-routing\'}},), is_leaf=True, yang_name="type", parent=self, path_helper=self._path_helper, extmethods=self._extmethods, register_paths=True, is_keyval=True, namespace=\'urn:ietf:params:xml:ns:yang:ietf-routing\', defining_module=\'ietf-routing\', yang_type=\'identityref\', is_config=True)'}

Note in the previous output how `static` (with no module name) is
allowed, but ietf-routing:static isn't.